//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YGOConsole.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YGOConsole.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4753,5320,5349,5581,5644,5947,6310,6311,6312,6313,4546,4434,4064,4272,5334,6037,6121,6196,6477,4352,4317,4932,4966,4345,4835,4856,4891,5330,6129,6213,4803,4849,4850,5331,4988,5210,5799,5914,6148,5124,.
        /// </summary>
        internal static string STARTER_DECK_2006 {
            get {
                return ResourceManager.GetString("STARTER_DECK_2006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7684,7685,4084,5581,6093,6172,6962,7192,7366,7686,7687,7688,7689,7690,4795,4917,4930,5318,5323,7691,7692,7693,5330,5905,4905,6213,5217,6999,7219,7223,6278,7694,7695,4355,4953,4836,5799,6217,4863,7013,7696,7697,7698,.
        /// </summary>
        internal static string STARTER_DECK_5Ds_2008 {
            get {
                return ResourceManager.GetString("STARTER_DECK_5Ds_2008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5946,6796,4790,7821,5336,7841,8280,5145,4608,5412,5661,6601,7701,7687,7688,4546,7686,7689,7537,7822,8281,4905,4910,4856,5330,5350,5162,6999,7743,7750,4352,7691,8282,4988,5133,5544,7636,7694,7695,4692,7679,7696,7551,.
        /// </summary>
        internal static string STARTER_DECK_5Ds_2009 {
            get {
                return ResourceManager.GetString("STARTER_DECK_5Ds_2009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5702,5876,7684,8861,8862,4507,5137,6599,7543,7687,7688,7701,7822,7985,8004,8009,8010,8439,8863,4910,4821,5328,5330,5538,5505,6130,6213,7691,8859,4836,4988,5544,5287,5620,5799,6278,6445,7755,8860,7551,7697,7835,.
        /// </summary>
        internal static string STARTER_DECK_5Ds_DUELIST_TOOLBOX {
            get {
                return ResourceManager.GetString("STARTER_DECK_5Ds_DUELIST_TOOLBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11769,4789,5762,5336,7121,6418,6547,8418,7871,8394,6545,6025,7094,7385,4342,5905,6213,4909,4905,4310,4327,5538,4887,5124,4836,4988,5102,4989,4804,.
        /// </summary>
        internal static string STARTER_DECK_DARK_LEGION {
            get {
                return ResourceManager.GetString("STARTER_DECK_DARK_LEGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4176,5349,5581,6960,9563,9564,9565,9566,9567,9568,9569,4915,4924,5488,5318,6687,7429,7431,8946,6457,9570,9571,9572,4909,4835,4354,5330,5538,5607,7125,9573,9574,4988,4836,4863,4887,5544,7230,7636,8354,9575,9576,9577,.
        /// </summary>
        internal static string STARTER_DECK_DAWN_OF_THE_XYZ {
            get {
                return ResourceManager.GetString("STARTER_DECK_DAWN_OF_THE_XYZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6527,4790,4538,5581,5643,6310,6311,6312,6313,5413,4108,5323,4771,5898,6111,5810,6253,6393,6477,6478,6415,4905,4910,5110,4891,5538,5905,6209,6213,5217,4803,6673,7125,4988,4836,4862,5799,5914,5994,4804,5124,.
        /// </summary>
        internal static string STARTER_DECK_JADEN_YUKI {
            get {
                return ResourceManager.GetString("STARTER_DECK_JADEN_YUKI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4088,4759,4010,4176,5146,4148,4299,4446,4057,4973,4980,5059,4919,4533,4022,4499,4434,4177,4054,4272,4120,4608,4075,4021,4327,4342,4348,4835,4843,4860,4874,4910,4906,4838,4842,4837,4338,4321,4662,4811,4818,4865,4836,4849,4850,4886,4851,4863,4696,4695,.
        /// </summary>
        internal static string STARTER_DECK_JOEY {
            get {
                return ResourceManager.GetString("STARTER_DECK_JOEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4007,4009,4011,4029,4032,4037,4039,4050,4072,4086,4096,4097,4200,4239,4247,4254,4273,4287,4293,4309,4330,4342,4352,4383,4384,4385,4388,4460,4472,4508,4603,4835,4836,4839,4843,4842,4848,4849,4852,4865,4747,4810,4172,4230,4339,4547,4695,4838,4850,4851,.
        /// </summary>
        internal static string STARTER_DECK_KAIBA {
            get {
                return ResourceManager.GetString("STARTER_DECK_KAIBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4007,4032,4037,4050,4072,4086,4097,4383,4385,4472,4743,5309,5336,5349,5409,4747,4172,4230,4547,4580,4930,5142,5335,5600,5601,4352,4835,4843,4842,4848,4810,4860,5099,4338,4856,4905,4663,4963,4966,5128,4675,4836,4865,4986,4988,4957,5210,5263,5348,5550,.
        /// </summary>
        internal static string STARTER_DECK_KAIBA_EVOLUTION {
            get {
                return ResourceManager.GetString("STARTER_DECK_KAIBA_EVOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4007,4219,4385,4032,5309,5336,5644,5504,5872,5004,9863,10024,5030,5521,5359,5409,5827,5488,6098,6099,6415,6978,7019,7896,8190,9910,10016,4342,5099,4856,4905,4909,5214,5345,5505,5979,5355,6003,5367,8422,9775,4836,5799,4675,4692,6278,7013,8845,.
        /// </summary>
        internal static string STARTER_DECK_KAIBA_RELOADED {
            get {
                return ResourceManager.GetString("STARTER_DECK_KAIBA_RELOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4737,4731,4732,4048,4050,4086,4080,4219,4387,4547,4929,4738,4108,4580,4507,4522,4126,4475,4617,4773,4735,4733,4734,4798,4317,4342,4348,4835,4843,4860,4326,4909,4905,4838,4842,4857,4341,4802,4888,4812,4836,4849,4850,4886,4863,4851,4876,4862,4992,4892,.
        /// </summary>
        internal static string STARTER_DECK_PEGASUS {
            get {
                return ResourceManager.GetString("STARTER_DECK_PEGASUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11768,9863,4008,11148,5353,6390,7246,5488,6196,4499,7610,4546,7436,4342,5905,6213,4909,4905,5607,4317,4327,4887,5124,10550,4836,4988,4989,4804,.
        /// </summary>
        internal static string STARTER_DECK_SABER_FORCE {
            get {
                return ResourceManager.GetString("STARTER_DECK_SABER_FORCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6735,4790,5027,5581,5705,5762,6383,6413,6497,5413,4108,6201,5810,6384,6385,6386,6387,6738,6736,6745,6937,4317,4905,4910,4891,5432,5905,5505,5983,6266,5217,4803,4836,4862,4863,5799,6278,4804,5124,6445,6747,.
        /// </summary>
        internal static string STARTER_DECK_SYRUS_TRUESDALE {
            get {
                return ResourceManager.GetString("STARTER_DECK_SYRUS_TRUESDALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9863,4176,6961,9563,9564,9619,9878,9621,9565,9569,6390,8946,5810,5318,4608,4054,4915,4924,9570,9764,9572,9676,4354,4909,4835,5726,5328,7399,9781,9574,5544,4836,4988,5124,5994,4989,7636,4863,9575,10125,10126,10127,10128,.
        /// </summary>
        internal static string STARTER_DECK_XYZ_SYMPHONY {
            get {
                return ResourceManager.GetString("STARTER_DECK_XYZ_SYMPHONY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4008,4012,4013,4028,4033,4041,4044,4045,4047,4065,4066,4071,4080,4103,4117,4133,4142,4184,4287,4308,4329,4342,4348,4439,4476,4835,4836,4839,4843,4842,4849,4860,4879,4880,4881,4882,4883,4884,4885,4886,5099,4821,4230,4335,4341,4507,4695,4838,4850,4851,.
        /// </summary>
        internal static string STARTER_DECK_YUGI {
            get {
                return ResourceManager.GetString("STARTER_DECK_YUGI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4041,4008,4012,4013,4028,4033,4044,4047,4066,4080,4287,4881,4753,5320,5581,4880,4507,4054,4064,4915,4929,5245,5658,4370,4676,4342,4348,4835,4842,4860,4885,4821,4838,4906,4310,4327,4909,4937,4354,4844,4836,4886,4862,4863,4355,4987,4953,5130,5397,5544,.
        /// </summary>
        internal static string STARTER_DECK_YUGI_EVOLUTION {
            get {
                return ResourceManager.GetString("STARTER_DECK_YUGI_EVOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4041,4008,4080,4028,4881,4538,5581,4064,4983,5139,4766,5648,5649,5651,5655,6040,6162,6164,6151,6155,6156,6977,5869,6150,4342,4354,4317,4909,5213,5432,5166,6057,5752,6995,6169,5743,9775,4836,4886,4887,4355,4989,5124,5681,5857,6445,.
        /// </summary>
        internal static string STARTER_DECK_YUGI_RELOADED {
            get {
                return ResourceManager.GetString("STARTER_DECK_YUGI_RELOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10024,5644,7193,4368,5581,5320,7276,4008,11134,11135,11136,11137,11138,11139,11140,11141,11142,11143,11144,11145,11146,11147,5217,4909,9764,4310,7125,6213,6129,5607,4836,5799,5544,4988,4675,5915,6071,5210,4862,4863,.
        /// </summary>
        internal static string SUPER_STARTER_SPACE_TIME_SHOWDOWN {
            get {
                return ResourceManager.GetString("SUPER_STARTER_SPACE_TIME_SHOWDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4714,10131,4881,4008,7276,10564,10565,10566,9618,9877,10028,9563,9564,9620,9621,9723,10027,9879,5318,5651,10567,9570,9662,9663,9764,10181,10085,5327,5328,5330,10568,9856,9784,10196,9691,9574,4675,4988,4989,7349,9575,9914,.
        /// </summary>
        internal static string SUPER_STARTER_V_FOR_VICTORY {
            get {
                return ResourceManager.GetString("SUPER_STARTER_V_FOR_VICTORY", resourceCulture);
            }
        }
    }
}
