//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YGOConsole.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YGOConsole.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4007,4009,4011,4029,4032,4037,4039,4050,4072,4086,4096,4097,4200,4239,4247,4254,4273,4287,4293,4309,4330,4342,4352,4383,4384,4385,4388,4460,4472,4508,4603,4835,4836,4839,4843,4842,4848,4849,4852,4865,4747,4810,4172,4230,4339,4547,4695,4838,4850,4851,.
        /// </summary>
        internal static string STARTER_DECK_KAIBA {
            get {
                return ResourceManager.GetString("STARTER_DECK_KAIBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4008,4012,4013,4028,4033,4041,4044,4045,4047,4065,4066,4071,4080,4103,4117,4133,4142,4184,4287,4308,4329,4342,4348,4439,4476,4835,4836,4839,4843,4842,4849,4860,4879,4880,4881,4882,4883,4884,4885,4886,5099,4821,4230,4335,4341,4507,4695,4838,4850,4851,.
        /// </summary>
        internal static string STARTER_DECK_YUGI {
            get {
                return ResourceManager.GetString("STARTER_DECK_YUGI", resourceCulture);
            }
        }
    }
}
